language: node_js
node_js:
  lts/*
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
after_script:
  - cat ./coverage/lcov.info | coveralls
after_success:
  - yarn generate
deploy:
  provider: netlify
  site: $NETLIFY_SITE
  auth: $NETLIFY_AUTH
  dir: "dist/"
  cleanup: true
  prod: true
  edge: true