language: node_js
node_js:
  lts/*
os:
  - osx
branches:
  only:
  - master
cache:
  directories:
    - node_modules
script:
  - npm run test
  - npm run generate
after_script:
  - cat ./coverage/lcov.info | coveralls
deploy:
  provider: netlify
  site: $NETLIFY_SITE
  auth: $NETLIFY_AUTH
  dir: "./dist/"
  cleanup: true
  prod: true
  edge: true