language: node_js
node_js:
  lts/*
env:
  - NETLIFY_SITEID=<site>
  - NETLIFY_AUTH=<auth>
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
after_script:
  - cat ./coverage/lcov.info | coveralls
deploy:
  provider: netlify
  site: <site>
  auth: <auth>
  dir: "dist/"
  edge: true