language: node_js
node_js:
  lts/*
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
after_script:
  - cat ./coverage/lcov.info | coveralls
deploy:
  provider: netlify
  site: NETLIFY_SITE_ID
  auth: NETLIFY_AUTH
  dir: "dist/"
  edge: true